### ISSUE TITLE
How you add an App in call's window?

### ISSUE THREAD

**Issue by stefan2410** [microsoft/Broadcast-Development-Kit-Meeting-App#13]
@JonatanMedinilla 
How did  you get the option Add an App in the Teams Client ?
![Capture](https://user-images.githubusercontent.com/1259393/126743571-88a12f92-9844-479d-a5c9-18696ef4bbee.JPG)

**Comment by verdua** [comment]
Hi @stefan2410
In order to upload custom apps into Teams, this option has to be enabled in the 365 tenant. Does your organization have the **_Upload custom apps_** option enabled in the Microsoft 365 Tenant? 

You can take a look into this [Microsoft documentation](https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/build-and-test/prepare-your-o365-tenant#enable-custom-teams-apps-and-turn-on-custom-app-uploading) to enable it.

**Comment by stefan2410** [comment]
Hi @verdua  from the admin center we have enabled  in the global policy the Upload custom apps.
But I have not seen the option inside the call's window.  Only in the Teams client tabs or else.

**Comment by stefan2410** [comment]
@JonatanMedinilla @verdua  Does  the "Add an App" option appears only in scheduled meetings ?

**Comment by sw-dcherubini** [comment]
>  Does the "Add an App" option appears only in scheduled meetings ?

@stefan2410 I tested this just now and I can see the "Add an App" option in scheduled meetings, but not if I use the "Meet now" meeting in Teams.

By the way, I'm using the "Developer Preview" in Teams, but I don't this is a feature exclusive to the developer preview.

**Comment by AaronLinne** [comment]
@stefan2410 yes, you must have the meeting already scheduled to add a meeting extension to it.

**Comment by stefan2410** [comment]
Thanks guys.   This option should be implemented for all kind of calls .
